### ISSUE TITLE
Connect route components with route nodes to resolve transition

### ISSUE THREAD

**Issue by jaysoo** [mobx-little-router/mobx-little-router#18]
Need to think of a good way to communicate between component and its node.

Something like:

```js
import { when } from 'mobx'

const config = {
  path: '',
  data: {
    isTransitioned: false
  },
  onTransition: async (node) => {
    return new Promise(res =>   {
      when(() => node.value.data.isTransitioned,
      res)
    })
  }
}

class Outlet extends Component {
  componentDidMount() {
    runInAction(() => {
      this.props.routeNode.value.data = true
    })
  }
}

```

**Comment by corbanbrook** [comment]
mobx-little-router-react now includes middleware which transforms the config to allow for an animate: true flag which will add a custom onTransition handler `handleAnimatedTransition` which incorporates the ideas presented above.
