### ISSUE TITLE
SSR example should use JSX

### ISSUE THREAD

**Issue by jaysoo** [mobx-little-router/mobx-little-router#20]
The code is quite noisy. We should just use babel-node and the react preset.

**Comment by pkieltyka** [comment]
it would be nice if the `ssr` or `basic` example worked as a universal app

**Comment by jaysoo** [comment]
SSR can also boot up the JS on client.. might be nice to show how that hooks up.

**Comment by pkieltyka** [comment]
Agreed

**Comment by jaysoo** [comment]
Closing this one (thanks @averted!)

New one opened for adding client-side loading in SSR. https://github.com/mobx-little-router/mobx-little-router/issues/34
