### ISSUE TITLE
RFC: Add support for route data and effects

### ISSUE THREAD

**Issue by jaysoo** [mobx-little-router/mobx-little-router#55]
Currently we can only resolve effects inside lifecycle methods (`willActivate`, `willResolve`, etc.). This isn't granular enough when you mix in multiple effects and multiple data dependencies.

This proposal will try to solve two problems:

1. How do we configure route-specific effects, such as data loading, mutations, etc.
2. How do we pass observable data to a route handler.

Both of these problems should be solve in a way that does not require logic to bleed outside of the route itself.

## Some code

This is the current example we can use when experimenting with reference implementation.

```js
// @flow
declare const router: any
declare class AccountsStore {}
declare class HubsStore {}
declare class HubPostsStore {}
declare class AccountsCommands {}
declare class HubsCommands {}
declare class Outlet {}
declare const fetchHub: Function
type IAccount = {}
type IHub = {}
type IPost = {}

const ROUTES = [{
  key: 'accountRoot',
  path: '/:username',
  computed(router) {
    const store = router.getContext().getInstance(AccountsStore)
    return {
      get account(): IAccount | null {
        const { username } = this.params
        return store.find(acct => acct.username === username)
      }
    }
  },
  subscriptions(router) {
    const cmds = router.getContext().getInstance(AccountsCommands)
    const { params } = this
    // Returns a disposer when the route is destroyed (e.g. when router is stopped).
    return autorun(() => cmds.fetchAccount(params.username))
  },
  component: ({ route }) => (
    <route.Instance>
      { ({ computed, state, effects }) => (
        <div>
          <h1>{ computed.account ? computed.account.name : '...' }</h1>
          <Outlet/>
        </div>
      ) }
    </route.Instance>
  ),
  children: [{
    key: 'hubRoot',
    path: '/:hubUid',
    state: { isPending: false },
    computed(router) {
      const store = router.getContext().getInstance(HubsStore)
      const accountRoot = router.select({
        accountRoot: { computed: ['account'] }
      })
      return {
        get hub(): IHub | null {
          const { hubUid } = this.params
          return store.find(hub => hub.uid === hubUid)
        },

        get isPending() {
          return this.state.isPending
        },

        get isReady(): boolean {
          if (this.state.isPending) {
            return false
          } else {
            return accountRoot.computed.account && this.hub
          }
        }
      }
    },
    subscriptions(router) {
      const cmds = router.getContext().getInstance(HubsCommands)
      const { params, state } = this
      const data = router.select({
        accountRoot: {
          params: ['username']
        }
      })

      // Returns a disposer when the route is destroyed (e.g. when router is stopped).
      return autorun(() => {
       // Must "dot-into" the data synchronously or else reaction will not be set up correctly.
        const response = cmds.fetchHub(data.accountRoot.params.username, params.hubUid)
        Promise.resolve()
          .then(() => state.isPending = true)
          .then(() => response)
          .catch(err => console.log(err))
          .then(() => state.isPending = false)
      })
    },
    component: ({ route }) => (
      <route.Instance>
        { ({ computed, state, effects }) => (
          <div>
            { computed.isReady
              ? (
                <div>
                  <h2>{ computed.hub ? computed.hub.name : '...' }</h2>
                  <Outlet/>
                </div>
              )
              : <div>Loading...</div>}
          </div>
        ) }
      </route.Instance>
    ),
    children: [{
      key: 'hubPosts',
      path: '/',
      state: {
        // Storing data needed to fetch more posts.
        $resource: null
      },
      computed(router) {
        const store = router.getContext().getInstance(HubPostsStore)
        const data = router.select({
          hubRoot: { computed: ['hub'] }
        })
        return {
          get posts(): IPost[] | null {
            const { hub } = data
            return store.getPosts(hub)
          }
        }
      },
      effects(router) {
        const cmds = router.getContext().getInstance(HubsCommands)
        const { state } = this
        return {
          requestMorePosts() {
            cmds.fetchMorePosts(state.$resource)
          }
        }
      },
      subscriptions(router) {
        // Returns a disposer when the route is destroyed (e.g. when router is stopped).
        return autorun(() => cmds.fetchPosts(this.computed.hub))
      },
      component: ({ route }) => (
        <route.Instance>
          { ({ computed, state, effects }) => (
            <div>
              <ul>
                { computed.posts.map(p => <li key={p.id}>{ p.title }</li>) }
              </ul>
              <button onClick={effects.requestMorePosts}>
                Load More
              </button>
            </div>
          ) }
        </route.Instance>
      )
    }]
  }]
}]
```

## Design considerations

* `router.Instance` is a context consumer that pipes route instance members into the provider. This is intentionally hidden from outside world and only available within the immediate `component`. By encapsulating this consumer, we avoid the the temptation to create "god" objects (like `HubUIStore`).

**Comment by validkeys** [comment]
@jaysoo why is the params property and object vs. array of param names?

```javascript
      const data = router.select({
        accountRoot: {
          params: { username: null }
        }
      })
```

Instead of:

```javascript
      const data = router.select({
        accountRoot: {
          params: ['username']
        }
      })
```

**Comment by jaysoo** [comment]
@validkeys The value is the default value... if we go with array it'll implicitly be `null`. Not sure if we need to specify the default explicitly or not.

**Comment by validkeys** [comment]
@jaysoo I see. Is there a difference between route params `hubs/:hubId` and queryParams? I can see wanting to set a default for query params but not route params

**Comment by jaysoo** [comment]
@validkeys query params have a global scope, like `?foo=1` is the same `foo` for every route. Route params could share same name but have different value within the route.

```js
const ROUTES = [{
 key: 'a',
 path: '/widgets/:id/items',
 children: [{ key: 'b', path: '/:id' }]
}]
```

Both `a` and `b` routes have `id` param, but they are bound to different values from the URL.

We can probably just say, `null` is the default value for everything and use arrays. If the user needs to set it differently, they can add that logic in userland.

**Comment by jaysoo** [comment]
Updated example so `params` selection is just a list now.

**Comment by corbanbrook** [comment]
im wondering if we even need `<route.Instance>` context setup. 

we could easily just pass in the computes via props into the route handler. and then use `router.select` from other compoments if they need access.

**Comment by corbanbrook** [comment]
would be nice to have a config specific for autoruns so we can initialize and dispose as the route is activated/deactivated

**Comment by corbanbrook** [comment]
for select and default properties we could support array of strings|objects for terseness and power when we need it.

```js
      const data = router.select({
        accountRoot: {
          params: ['username', { name: 'tab', default: 'home' }]
        }
      })
```

**Comment by jaysoo** [comment]
@corbanbrook As discussed offline, `<route.Instance>` may allow us to properly type the polymorphic `computed` and `effects` objects. We may want to explore the types further outside of this project if we wish to make the config more succinct.

We may want to hold off on implementing `created` and `component` sections of the config until we're happy with the spec. Let's stick to just `effects`, `state`, and `computed` for now.

For **default values**, it probably is best to leave it to userland since the only information we care about is if the param has matched (`string`) or not (`null`). The `computed` can prepare these defaults if they are needed by the component.

**Comment by corbanbrook** [comment]
`created` has been renamed to `subscriptions`
