### ISSUE TITLE
2.0.0 and React context

### ISSUE THREAD

**Issue by KatSick** [mobx-little-router/mobx-little-router#59]
Hi,

I'm using your 2.0.0-4 version of router and it works really nice. 
However, I noticed that you are using createContext from React16.4+. This will limit usage of your awesome router, but I understand that migration to new context is needed.
What about some polyfills like https://github.com/jamiebuilds/create-react-context ?

Are you interested in that kind of PR?

**Comment by jaysoo** [comment]
Hey @KatSick, that's a good point. We can definitely make use of this polyfill. 

If you want to open up a PR against the `v2.0.0` branch we can look at merging that in.

Cheers!

**Comment by jaysoo** [comment]
@KatSick Thanks! It's merged and will be released in the next canary version.
